// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daplngwknqndzhwauekp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGxuZ3drbnFuZHpod2F1ZWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjk5MDksImV4cCI6MjA2MDgwNTkwOX0.N46fA91kAtNJf69Rc4yA28-Ib6qIrhXgD1iot9xm0fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);